### ISSUE TITLE
Chrome version

### ISSUE THREAD

**Issue by mrvanes** [UNINETT/SAML-tracer#15]
The only reason I still fire up Firefox now and then is for SAML-tracer. What are the odds of a Chrome version? There still is no good replacement in that arena.

**Comment by olavmrk** [comment]
Unlikely to be created by me at least -- I have no experience with Chrome extension-development, and I don't have time available to create such an extension in the foreseeable future.

If someone else wants to create one, they are certainly free to use the source code of this extension as a starting point. I don't think much of the code can be reused though, since the majority of code is relatively browser specific. (Dealing with user interface and network request retrieval -- the parts that decode and process SAML messages is actually relatively small.)

**Comment by thijskh** [comment]
You might want to take a look at https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace
