### ISSUE TITLE
export function

### ISSUE THREAD

**Issue by relaxi** [UNINETT/SAML-tracer#25]
Can you add the export function again?

**Comment by Clark76** [comment]
Along with export, the import function would be very helpful.

**Comment by khlr** [comment]
For anyone interested in this issue: I'll start working on it soon. I expect to have some free time for this after Christmas.

**Comment by khlr** [comment]
Some news on the progress: I think I'm halfway through with the export-part. Although I think that I could still spend a lot more time on UX things ;-)

Does anybody have an old export at hand? When I start working on the import-part (maybe within the next week) it'd be nice if I had an old exported file so that I can try to ensure that even old exports can be imported again.

**Comment by thijskh** [comment]
Great news! I don't have any saved traces handy that I can share. But to me, backwards-compatibility is not very essential there. Usually there's a small timeframe between the trace being generated and it being imported, I hardly ever try to import an trace older than say a few days.

**Comment by tvdijen** [comment]
I will look up an old trace for you tomorrow @ work... Must have a couple in my mail

**Comment by tvdijen** [comment]
There ya go!
[samltracer_export.txt](https://github.com/UNINETT/SAML-tracer/files/1597112/samltracer_export.txt)

**Comment by khlr** [comment]
If nothing unexpected comes up, I'm quite confident that I'll be able to finalize my changes tomorrow and submit a pull request! 🤗
